server:
  error:
    include-message: always
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/proposta?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security.oauth2.resourceserver.jwt:
    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/proposta}
    jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/proposta/protocol/openid-connect/certs}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging.level.br.com.zup.proposta.analise.AnaliseCliente: DEBUG
logging.level.br.com.zup.proposta.cartao.ClienteCartao: DEBUG
logging.level.br.com.zup.proposta.compartilhado.seguranca.AuthClient: DEBUG


management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: info,metrics,health
  endpoint:
    health:
      probes:
        enabled: true

opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    service-name: ${spring.application.name}
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}

api:
  auth: ${API_AUTH}
  analise: ${API_ANALISE}
  cartoes: ${API_CARTAO}